"""add_reset_password_otp_fields

Revision ID: 615bc9ca7bf8
Revises: 5dfe3bc5d043
Create Date: 2025-10-27 03:44:41.545204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '615bc9ca7bf8'
down_revision: Union[str, None] = '5dfe3bc5d043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_otp', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_password_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'reset_password_token')
    op.drop_column('users', 'reset_password_token_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_password_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'reset_password_otp_expires_at')
    op.drop_column('users', 'reset_password_otp')
    # ### end Alembic commands ###
