"""Add new_email and new_phone columns to user table

Revision ID: 8779e03d67f4
Revises: e43fbae79185
Create Date: 2025-10-22 17:28:09.877242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8779e03d67f4'
down_revision: Union[str, None] = 'e43fbae79185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('new_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_phone')
    op.drop_column('users', 'new_email')
    # ### end Alembic commands ###
